### PR TITLE
[WIP] ADV Getting rid of predictions in the DB 

### PR DESCRIPTION
**Pull request by kegl**

### CODE REVIEW

**Comment by rth** [comment]
LGTM, thanks @kegl . I checked this works on the server (even without a DB migration visibly). Good to remove unused code.

**Comment by kegl** [comment]
Yes, it was already removed by @glemaitre I think.

**Comment by glemaitre** [comment]
Yep, I think that I commented out the part that where storing the predictions but letting the code as is just in case that it was not a wise choice. I think that we did not get into trouble, so clean-up was a great thing.

**Comment by rth** [comment]
Great!

**Pull request merged**
