### PR TITLE
Handle error during setup/launch of worker in Dispatcher

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by glemaitre** [comment]
Do we need some test here to check that we will raise the error and stop the worker properly.

**Comment by jorisvandenbossche** [comment]
Probably yes, but for now this only affects the aws one (and I am also not sure for aws how to reliably trigger an error, maybe by giving an non-existing AMI id). 
Is there a way for the conda worker to have a failed set-up ?

**Comment by glemaitre** [comment]
Requesting an environment that does not exist
 

                                                                                                                                      
 

                            
     

Sent from my phone - sorry to be brief and potential misspell.

**Comment by lucyleeow** [comment]
Address instance not launching properly - so hopefully can close #243

**Comment by lucyleeow** [comment]
ping @maikia @agramfort

**Pull request merged**
