### PR TITLE
FIX better appearance on mobile

### PR DESCRIPTION
**Pull request by lucyleeow**
Appearance is pretty much the same on desktop. Appearance on mobile (simulation of iphone 6/7/8 plus) is below (the aim was 'acceptable'):

homepage
Screenshot_2020-01-28 Approve users - RAMP
Screenshot_2020-01-28 User - RAMP

### CODE REVIEW

**Comment by lucyleeow** [comment]
Fix logo on home page - appearance on mobile:

Screenshot_2020-01-28 RAMP collaborative data science challenges(1)

**Comment by lucyleeow** [comment]
cc @agramfort @glemaitre

**Comment by agramfort** [comment]
feel free to merge so we test on  dev server. thx @lucyleeow !

**Comment by glemaitre** [comment]
Actually I don't have the sign-up and log-in button in the menu on my phone. Do you have the same issue?

**Comment by lucyleeow** [comment]
Yes actually I forgot about this. For some reason it doesn't show up on the home page but in other pages there is a button on the top right (icon is 9 squares):
Screenshot_2020-01-29 Login - RAMP

and when you click it you get the log on and sign in buttons:

Screenshot_2020-01-29 Login - RAMP(1)

Any idea why?

**Pull request merged**
