### PR TITLE
UI Don't pre-select all users for approval

### PR DESCRIPTION
**Pull request by rth**
In the approval admin tab, this removes the pre-selection of all users to approve for site or event sign up.

For instance, there were quite a few spam sign ups on ramp.studio lately and the current default can result in accidentally approving those spam accounts, particularly by new admins.

If all users need to be selected, it's still easy enough with 1 click.

### CODE REVIEW

**Comment by kegl** [comment]
LGTM, thanks @rth . Maybe @agramfort can look at it, a 30sec decision. I think it's a good change also for ramp.studio.

**Comment by frcaud** [comment]
LGTM @rth. It will be useful for ramp.studio. Thanks !

**Review by frcaud — COMMENTED** [review]
code changes LGTM

**Comment by rth** [comment]
Thanks! The CircleCI  issue is unrelated, I'll fix it in a separate PR.

**Pull request merged**
