### PR TITLE
convert bagged scores to float

### PR DESCRIPTION
**Pull request by frcaud**
In order to avoid DB error: ```can't adapt type 'numpy.int64'```

### CODE REVIEW

**Comment by frcaud** [comment]
@rth could you review this change please ?

**Review by agramfort — APPROVED** [review]
I confirm it's a real bug and that fixes it.

@frcaud I think this deserves a changelog entry somewhere.

**Comment by rth** [comment]
Thanks @frcaud !

**Comment by agramfort** [comment]
@rth can you give us a hand to make a tiny minor release and update the server? I don't think I can do the release myself.

maybe @glemaitre you have a minute otherwise to help here?

🙏 🙏 🙏

**Comment by glemaitre** [comment]
I can try to make the release now.

**Comment by agramfort** [comment]
❤

**Comment by rth** [comment]
As far as I remember there were changes in this release requiring a DB migration. Or did you manage to update without it @glemaitre ?

**Comment by glemaitre** [comment]
I made the release, I did not update the server :) If you could give a hand to upgrade the server because I am a bit rusty when it comes to DB migration since I did not do it in the last 2 years :).

**Comment by rth** [comment]
That works. I'll look into updating the server.

**Comment by glemaitre** [comment]
pinging @agramfort since they started the data challenge and he could tell you the worker that are running currently

**Comment by rth** [comment]
I mean if it's just for this fix the easiest is to make a patch 0.8.2 release just with this change and update the server with that.  For the DB migration, there will be some downtime and I would rather not do it if a data challenge tomorrow is depending on it :)

**Comment by agramfort** [comment]
0.8.2 and minor update would for me.

@rth any help is appreciated :)

**Comment by rth** [comment]
OK, the 0.8.2 release with this fix is done and the server updated. I restarted the frontend and the schedulers I could find.

**Comment by frcaud** [comment]
Great ! Thanks @rth

**Pull request merged**
