### PR TITLE
Improve classify challenge

### PR DESCRIPTION
**Pull request by maikia**
1. It makes shorter/clearer the message about viewing problems through classify.
2. If there are no problems in classify category it displays the message that there are no problems in this category
3. It adds not classified heading for problems which are not classified to any category

**- before:**
message on the problems list:
before1

classified page:
before2

**- after:**
message on the problems list:
after1

classified page:
after2

### CODE REVIEW

**Comment by lucyleeow** [comment]
It's failing because there are some hard coded tests that check for specific events in data domain. This test doesn't seem very robust. Any suggestions @agramfort @glemaitre

**Comment by glemaitre** [comment]
If I remember correctly, we deploy Boston and we check that the domains related to Boston are in the webpage. So this is hardcoded but because of what we deploy.

**Comment by glemaitre** [comment]
So in case, you change something regarding the toy dataset, you can adapt the test accordingly even if it is hard-coded value.

**Comment by agramfort** [comment]
thx @maikia 

website updated

**Comment by maikia** [comment]
thanks @agramfort @lucyleeow @glemaitre

**Pull request merged**
