### PR TITLE
[DOC] adding note for ami_image_name generic name

### PR DESCRIPTION
**Pull request by frcaud**
When filling 'config.yml' file for an event and when using AWS worker, one can put generic AMI name under 'ami_image_name'. It will automatically point to the latest version of the image created running the pipeline.

### CODE REVIEW

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
@frcaud any idea why CIs fail here?

**Review by tomMoral — APPROVED** [review]
LGTM!

**Comment by frcaud** [comment]
@agramfort green now. Seems GitHub actions were having issues previously.

**Comment by agramfort** [comment]
Thx @frcaud

**Pull request merged**
