### PR TITLE
MAINT: move some utils from ramp-utils to ramp-database

### PR DESCRIPTION
**Pull request by glemaitre**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Is the `import_module_from_source` potentially something to use in ramp-workflow as well? (which would be a reason to keep it in ramp-utils)

**Comment by glemaitre** [comment]
Yes it is. Another solution is to duplicate. 
We can let it now for the moment and see if we can remove the ramp utils

**Comment by jorisvandenbossche** [comment]
ramp-utils has the core cli (which we should add as dependency for ramp-workflow at some point), so that's a reason to keep it?

**Comment by glemaitre** [comment]
yep until ramp-utils can be installed in standalone for ramp-workflow.
I think that we can keep as it is now.

**Pull request closed without merging**
