### PR TITLE
FIX font on mobile problem page

### PR DESCRIPTION
**Pull request by lucyleeow**
Appearance on mobile
Screenshot_2020-02-03 User - RAMP

### CODE REVIEW

**Comment by agramfort** [comment]
thanks @lucyleeow ! did you do a pass on all pages in your testing ?

**Comment by lucyleeow** [comment]
These changes are specific for this page so shouldn't affect other pages.

There may be UI issues on other pages though - e.g. https://github.com/paris-saclay-cds/ramp-board/pull/376#issuecomment-579579501 I'm not sure about how to fix this issue so it would take someone else  (e.g. @maikia) the same time as it would take me to fix it.

Happy to fix other UI issues that I know how to fix.

**Comment by lucyleeow** [comment]
Problems page:
- increased text font
- Top navbar icons are bigger
- screen size aware padding
Screenshot_2020-02-03 User - RAMP(1)

- Teaching and description pages have larger font on mobile
- challenge page has smaller font on mobile

Still to fix - the top navbar with RAMP and icons is too large for the challenge and event page on mobile. Could reduce font on the event pages.
I won't have time to do this before I leave - maybe @maikia can look into it.

**Comment by glemaitre** [comment]
Merging this PR and we will open a new one with the navbar

**Comment by agramfort** [comment]
can you update server so we can see how far we are?

>

**Pull request merged**
