### PR TITLE
BUG: dispatcher - test that error message is stored correctly in database

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by rth** [comment]
Unless you are saying that it's actually not stored in the database, and so it's another issue than https://github.com/paris-saclay-cds/ramp-board/issues/179 ?

**Comment by jorisvandenbossche** [comment]
Yeah, this is not fixing anything (just adding a test I wrote to notice it is already working as expected). See https://github.com/paris-saclay-cds/ramp-board/issues/179 for the explanation.

**Comment by jorisvandenbossche** [comment]
Funny, this is actually failing on travis :-) 
So travis has the same behaviour as we see on Amazon or on your server, but different from our local laptops.

In any case, that means we first have to fix it properly before merging this.

**Comment by glemaitre** [comment]
One more fix!!!

**Comment by rth** [comment]
Thanks for addressing this! Can confirm it resolves https://github.com/paris-saclay-cds/ramp-board/issues/179

**Pull request merged**
