### PR TITLE
[MRG] MAINT: moving databoard module one level down

### PR DESCRIPTION
**Pull request by aboucaud**

### CODE REVIEW

**Comment by glemaitre** [comment]
Can we do that after my PR :)

**Comment by aboucaud** [comment]
Then hurry up, I'm almost green :)

**Comment by jorisvandenbossche** [comment]
Can you try merging this in your PR? (just as a try, we were wondering if that would work :-))

**Comment by jorisvandenbossche** [comment]
But something else, I would try to finish your current PR, and do a futher batch of clean-ups in a next PR. As there are already some things in your PR I would want to use for the testing.

**Comment by glemaitre** [comment]
> But something else, I would try to finish your current PR, and do a futher batch of clean-ups in a next PR. As there are already some things in your PR I would want to use for the testing.

We can merge my PR now. I will just freeze what I have now. I would like that we fix the issue with the password checking thought.

**Comment by aboucaud** [comment]
It's green now @glemaitre..just sayin'

**Pull request merged**
