### PR TITLE
Add a github actions CI setup

### PR DESCRIPTION
**Pull request by rth**
Closes https://github.com/paris-saclay-cds/ramp-board/issues/459

### CODE REVIEW

**Comment by rth** [comment]
Could someone please check that github actions are indeed enabled in the repo settings (including on PRs)? Not sure why they are not triggering. Thanks!

cc @agramfort @lucyleeow

**Comment by rth** [comment]
Actions trigger on a test upstream branch https://github.com/paris-saclay-cds/ramp-board/tree/test-gh-actions, so they probably just need to be enabled to trigger on PRs from forks in the repo setting for this to work.

**Comment by agramfort** [comment]
@rth you have now admin rights :)

**Comment by lucyleeow** [comment]
@rth it might be because this PR is a draft: https://github.community/t/github-actions-not-being-triggered-on-draft-pr/16390

I couldn't figure out how to change it from a draft, maybe you have to do it yourself?

**Comment by lucyleeow** [comment]
I think it's working now?

**Comment by lucyleeow** [comment]
Doesn't seem to like python version?
```
Error: The value of "python-version" you provided was , which is invalid.
```

**Comment by rth** [comment]
Thanks @lucyleeow and @agramfort !

I think this is good to go. All the same tests are run, and the coverage numbers are the same aside for 2 lines difference (that I think is due to codecov not being run for the last PR on master).

A nice thing is that we can have a separate flake8 job instead of doing that as part of tests (which is much faster).

One difference is that postgress is currently used from a separate docker image instead of the one from conda. That shouldn't matter. I'm actually not sure how the postgress process is run the background in TravisCI (I don't see the command anywhere).

Merging to unblock other PRs. But we can certainly improve on top of this.

**Comment by lucyleeow** [comment]
Thanks @rth !

**Pull request merged**
