### PR TITLE
ENH add fetcher for OSF data

### PR DESCRIPTION
**Pull request by glemaitre**
If we start to store data in OSF, we will need to fetch data from there.
We also need support for injecting private `token` since the data will be private.

### CODE REVIEW

**Comment by glemaitre** [comment]
TODO:

- [ ] Write some test event. Not that it was live tested with: https://github.com/ramp-data/air_passengers/pull/1

**Comment by glemaitre** [comment]
ping @agramfort

**Comment by agramfort** [comment]
a test will tell me if it's good :)

**Comment by glemaitre** [comment]
I merging after making a test for it.

**Pull request merged**
