### PR TITLE
pass on description / history

### PR DESCRIPTION
**Pull request by agramfort**
cc @lucyleeow @maikia 

for some reason some ramps are not visible as ramp-kits such as the variable stars one which was really cool. I would be great to put it online.

### CODE REVIEW

**Comment by lucyleeow** [comment]
@agramfort could you post a screenshot of the new about page?

**Comment by lucyleeow** [comment]
Amended history page:
image

Some information this page previously had will be moved to the teaching page. Thoughts welcome @agramfort @maikia @kegl

**Comment by agramfort** [comment]
I think you can add / keep some past events:

variable star classification <https://indico.lal.in2p3.fr/event/2797/> now
at https://github.com/ramp-kits/fan_revenue_prediction
autism https://github.com/ramp-kits/autism
https://paris-saclay-cds.github.io/autism_challenge/

and at the end of the list of past events I would point to
https://github.com/ramp-kits/

thx

>

**Comment by lucyleeow** [comment]
image

@agramfort

**Comment by lucyleeow** [comment]
Merged as green - amendments can be made later.

**Comment by agramfort** [comment]
thx @lucyleeow !

**Pull request merged**
