### PR TITLE
BUG always make copy of external data

### LINKED ISSUE #409: Issue with external data symlink
When introducing the changes from @tomMoral (not to blame because it was not tested :)), I did not pay attention and we introduce a big regression.

When a user sign-up to an event we make a copy of the starting kit and submit it (for setting up the sandbox). If the external data were inside, we copied this file. Now with the symlink, we synlink to the starting kit and at every submission, we symlink the external data to this first submission data which symlink to the starting-kit external data.

Now when a user upload a file, it will be copied in place of the external data of the original kit where all the submissions are pointing to.

So the resolution is to make a hard-copy of the original external data when submitting the starting-kit. When uploading the data, we should replace the first submission and not the original data. We can check the diff on the `ramp.studio` server in production where I programmed this way in the past (including a parameter `hard_copy=True` for the original submission).

Be aware that this way one cannot download the external data from a previous submission because it will only be representative of the last submission uploaded.

### PR DESCRIPTION
**Pull request by glemaitre**
closes #409 

Always make a copy instead of trying to symlink. We should go from the principle that the data are always quite small.

### CODE REVIEW

**Comment by glemaitre** [comment]
ping @agramfort @rth

**Comment by glemaitre** [comment]
This PR needs to be back ported in 0.4.X for a bug fix release

**Comment by agramfort** [comment]
Looks good. Can we still put this code on server as soon as the FAN challenge is closed?

**Comment by glemaitre** [comment]
> Looks good. Can we still put this code on server as soon as the FAN challenge is closed?

Can I close FAN now?

**Comment by glemaitre** [comment]
or do you still have some activities happening there?

**Pull request merged**
