### PR TITLE
MAINT: remove user interaction

### PR DESCRIPTION
**Pull request by glemaitre**
@rth  Could you check if you still have some memory leak without tracking user interaction?

### CODE REVIEW

**Comment by rth** [comment]
I think user interactions just add transactions, so by disabling them, we will just make the leak less visible not really resolving it. cf related comment in https://github.com/paris-saclay-cds/ramp-board/issues/190#issuecomment-472862249

**Comment by glemaitre** [comment]
Yes, I still don't know where to specify where the option should be available.

**Comment by rth** [comment]
Maybe some environment variable as a start,
```py
def add_user_interaction(....):

    if not os.environ.get('RAMP_USER_INTERACTIONS', False):
        return None
    
```
?

**Comment by rth** [comment]
One reason I think interactions might be good to have is that, doing a load test (with multiple requests) on say just `/problems` should stress the database somewhat and see if we can reproduce the memory issues in #190 without doing any complicated actions.

**Pull request closed without merging**
