### PR TITLE
ADV FIX bokeh plot on admin dashboard

### PR DESCRIPTION
**Pull request by rth**
- improves bokeh 2.0+ compatibility (`previewsave` tool was replaced by `save`)
 - fix Jinja2 formatting issues in `dashboard_submissions.html`

This allows to display bokeh plots on the admin submission page again.

### CODE REVIEW

**Comment by agramfort** [comment]
is this a bug in master too?

**Comment by rth** [comment]
Yes, it's also a bug in master. Generally, that are several PRs in `advanced` that it would be really good port to master. Maybe next week, let's see what can be ported easily and that doesn't present backward incompatibility risks on the deployed ramp.studio server?

**Comment by agramfort** [comment]
@rth yes if you can help us with this on the ramp.studio server

it should be safe to do updates that are not touching the database

**Comment by rth** [comment]
Yes, I can help with that next week.

**Comment by agramfort** [comment]
thanks

much appreciated

>

**Pull request merged**
