### PR TITLE
[MRG] EHN create function to create RAMP admin

### PR DESCRIPTION
**Pull request by glemaitre**
Add a function to easily make a user RAMP admin

### CODE REVIEW

**Comment by rth** [comment]
Maybe you could take for this PR what was done for it in https://github.com/paris-saclay-cds/ramp-board/pull/276?

**Comment by glemaitre** [comment]
@rth I am actually stripping off #276 into small PRs and add tests.

**Comment by glemaitre** [comment]
This is the first one :) I am going to introduce all bug fixes that was introduce.

**Comment by kegl** [comment]
Thx a lot @glemaitre!

**Pull request merged**
