### PR TITLE
Release 0.4.3

### PR DESCRIPTION
**Pull request by lucyleeow**

### CODE REVIEW

**Comment by lucyleeow** [comment]
I don't know if this is correct. `bumpversion release` changed to 0.50 (major release - I was thinking it would be a minor one 0.4.3...). Is this right?

ping @glemaitre @agramfort

**Comment by agramfort** [comment]
@glemaitre knows better

>

**Comment by glemaitre** [comment]
You should create a branch 0.5.X instead of 0.4.3.

**Comment by glemaitre** [comment]
and the X is not a mistake  :) (not 0.5.0)

**Pull request closed without merging**
