### PR TITLE
enable login by email

### PR DESCRIPTION
**Pull request by maikia**
Login using username or e-mail will now work

### CODE REVIEW

**Comment by agramfort** [comment]
I assume you tested in the frontend?

diff looks good. Thanks for the quick fix!

**Comment by maikia** [comment]
I tested it locally in the frontend. yes.

**Comment by agramfort** [comment]
@kegl merge if it's ok for you. thx

**Comment by kegl** [comment]
LGTM, just a question: shouldn't we modify the login form from "username" to "username or email"? So users know they can type either?

**Comment by agramfort** [comment]
+1

>

**Comment by agramfort** [comment]
thx @maikia

**Pull request merged**
