### PR TITLE
FIX bokeh plot in admin dashboard (#461)

### PR DESCRIPTION
**Pull request by rth**
Backport of #461 to master.

### CODE REVIEW

**Comment by agramfort** [comment]
not clear what this fixes. I see the plot here https://ramp.studio/event_plots/meg_datacamp2020 for example

**Comment by rth** [comment]
I'm not in that event so I don't see it. But for https://ramp.studio/events/air_passengers_py4ds2020/dashboard_submissions for instance I see,

image

so no graph, with a `Uncaught SyntaxError: expected property name, got '{'` syntax error in the JavaScript console. This fixes it.

**Comment by rth** [comment]
For https://ramp.studio/events/meg_datacamp2020/dashboard_submissions I also see no plots, with the same error both in Chrome and Firefox. So I'm not sure why it's working for you..

**Review by agramfort — APPROVED** [review]
ok I can replicate !

**Comment by rth** [comment]
Merging with one approval as this should be very low risk and a useful bug fix.

**Pull request merged**
